language: python

python:
  - 3.6

services:
  - mysql

env:	    
  - DJANGO_VERSION=1.11.7

before_install:
  - mysql -e 'CREATE DATABASE IF NOT EXISTS censos;'
  - mysql -e --default-character-set=utf8 censos < create_database.sql
install:
  - pip install -q Django==$DJANGO_VERSION
  - pip install -r requirements.txt

script:
  - python censos/manage.py test censos/api/
