# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-12-04 17:34
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='censo',
            name='fecha_ini',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2017, 12, 4, 17, 34, 36, 437069, tzinfo=utc)),
        ),
    ]
