# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-12-04 17:34
from __future__ import unicode_literals

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_auto_20171204_1734'),
    ]

    operations = [
        migrations.AlterField(
            model_name='censo',
            name='fecha_ini',
            field=models.DateTimeField(blank=True, default=django.utils.timezone.now),
        ),
    ]
