# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-01-12 22:50
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_auto_20171221_1529'),
    ]

    operations = [
        migrations.AddField(
            model_name='censo',
            name='comunidad_autonoma',
            field=models.CharField(default='ANDALUCIA', max_length=50),
        ),
    ]
